# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo aks
  displayName: 'Running AKS using TF'
- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'id_az_rsa.pub'
- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    commandOptions: '- var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
    backendType: 'azurerm'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'tf-backend-rg'
    backendAzureRmResourceGroupLocation: 'westeurope'
    backendAzureRmStorageAccountName: 'salijinaks'
    backendAzureRmContainerName: 'salijinakscontainer'
    backendAzureRmKey: 'k8s-dev.tfstate'
    allowTelemetryCollection: true
